"""Example log parser — a copy-me template (committed as living documentation).

A parser transforms generic ``CompactLog`` rows into a leaner, business-specific form
before rendering, then the CLI prints them via ``render_parsed`` as ``ts | trace_id | msg``.

To build your own:
  1. Copy this file to ``<yourbiz>_parser.py`` in this folder (it will be git-ignored).
  2. Implement ``parse(rows) -> rows`` — do NOT mutate inputs; use ``dataclasses.replace``.
  3. (Optional) Implement ``report(rows) -> ReportModel`` to drive ``--report`` with
     business-specific KPIs, charts, and breakdowns. If you don't, the CLI falls
     back to ``build_generic_report``, which clusters by masked message signature.
  4. Call ``register("<yourbiz>", YourParser())`` at module level.
The module is auto-loaded on import, so ``zammadog cw ... --parser <yourbiz>`` just works.

This example does one common, framework-agnostic thing: many loggers emit
``<prefix> --- <logger> : <message>``; it keeps only the part after ``---``.
"""
from __future__ import annotations

from dataclasses import replace

from ..compact import CompactLog
from ..report import KPI, ReportModel, TableSection
from . import register

_SEP = " --- "


class ExampleParser:
    """Keeps only the text after a ``---`` separator; otherwise leaves the row untouched."""

    def parse(self, rows: list[CompactLog]) -> list[CompactLog]:
        out: list[CompactLog] = []
        for row in rows:
            msg = row.msg.split(_SEP, 1)[1] if _SEP in row.msg else row.msg
            out.append(replace(row, msg=msg.rstrip()))
        return out

    def report(self, rows: list[CompactLog]) -> ReportModel:
        """Trivial example report — copy and adapt for your business.

        Real parsers compute error-code frequencies, endpoint breakdowns, warn
        clusters, etc. Keep the analysis deterministic and cheap: the report is
        generated by code, not an LLM, so the math must be simple and exact.
        """
        total = len(rows)
        distinct_msgs = len({r.msg for r in rows})
        return ReportModel(
            title=f"Example report — {total} lines",
            kpis=[
                KPI("Total lines", str(total)),
                KPI("Distinct messages", str(distinct_msgs)),
            ],
            charts=[],
            sections=[
                TableSection(
                    title="Sample rows",
                    columns=["TS", "SVC", "MSG"],
                    rows=[[r.ts, r.svc or "-", r.msg[:120]] for r in rows[:50]],
                ),
            ],
        )


register("example", ExampleParser())
